language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t devtriskel/docker-angular -f Dockerfile.dev .

script:
  - docker run -it devtriskel/docker-angular ng test --watch=false
  - docker run -it devtriskel/docker-angular ng e2e --port 4202